version: '3'

services: 
    backend:
        build: 
            context: .
            dockerfile: Dockerfile
        ports: - 5000:5000
        restart: always
    frontend:
        build: 
            context: ./front-end
            dockerfile: Dockerfile
        ports: - 9090:3000
                    